DROP TABLE CLIENTE 		  	CASCADE CONSTRAINT;
DROP TABLE DOTTORE 		 	CASCADE CONSTRAINT;
DROP TABLE DONATORE 	 	CASCADE CONSTRAINT; 
DROP TABLE PAGAMENTO 	 	CASCADE CONSTRAINT; 
DROP TABLE FIALA_SEME	  	CASCADE CONSTRAINT; 
DROP TABLE FIALA_SANGUE  	CASCADE CONSTRAINT; 
DROP TABLE PRENOTAZIONE  	CASCADE CONSTRAINT; 
DROP TABLE SALA 		 	CASCADE CONSTRAINT; 
DROP TABLE CARTELLA_CLINICA CASCADE CONSTRAINT; 
DROP TABLE EFFETTUA_T 	    CASCADE CONSTRAINT;  
DROP TABLE TURNO 	     	CASCADE CONSTRAINT; 
DROP TABLE CRIOCELLA 	 	CASCADE CONSTRAINT; 
DROP TABLE FERTILITA 	 	CASCADE CONSTRAINT; 
DROP TABLE SANGUE 		 	CASCADE CONSTRAINT; 
DROP TABLE SPERMIOGRAMMA  	CASCADE CONSTRAINT; 
DROP TABLE GENETICO 	    CASCADE CONSTRAINT; 
DROP TABLE LAVORA_IN	  	CASCADE CONSTRAINT; 
DROP TABLE INSEMINAZIONE    CASCADE CONSTRAINT; 


DROP SEQUENCE ID_FIALA_SA_S; 
DROP SEQUENCE ID_FIALA_SE_S;  
DROP SEQUENCE ID_CRIO_S; 
DROP SEQUENCE ID_PREN_S; 
DROP SEQUENCE TURNO_DOTTORE;
DROP SEQUENCE ID_CC_S; 
DROP SEQUENCE COD_SANGUE_S; 
DROP SEQUENCE COD_SPERM_S; 
DROP SEQUENCE COD_GEN_S; 
DROP SEQUENCE COD_FERT_S; 
DROP SEQUENCE FATTURA_S; 
DROP SEQUENCE COD_INS_S; 

CREATE SEQUENCE ID_FIALA_SA_S; 
CREATE SEQUENCE ID_FIALA_SE_S; 
CREATE SEQUENCE ID_CRIO_S; 
CREATE SEQUENCE ID_PREN_S; 
CREATE SEQUENCE TURNO_DOTTORE; 
CREATE SEQUENCE ID_CC_S; 
CREATE SEQUENCE COD_SANGUE_S; 
CREATE SEQUENCE COD_SPERM_S; 
CREATE SEQUENCE COD_GEN_S; 
CREATE SEQUENCE COD_FERT_S; 
CREATE SEQUENCE FATTURA_S; 
CREATE SEQUENCE COD_INS_S; 


CREATE TABLE CLIENTE (
CF_CLI CHAR(16) PRIMARY KEY, 
NOME_CLI VARCHAR(15) NOT NULL, 
COGNOME_CLI VARCHAR(30) NOT NULL, 
DN_CLI DATE NOT NULL, 
SESSO_CLI CHAR(1), 
CITTA_CLI VARCHAR(20), 
VIA_CLI VARCHAR(30), 
TELEFONO_CLI CHAR(10) NOT NULL UNIQUE, 
PROV_CLI CHAR(2) NOT NULL, 
CONSTRAINT CHECK_SCLI CHECK(SESSO_CLI IN ('M','F'))
);


CREATE TABLE DOTTORE (
CF_DOT CHAR(16) PRIMARY KEY, 
NOME_DOT VARCHAR(15) NOT NULL, 
COGNOME_DOT VARCHAR(30) NOT NULL, 
DN_DOT DATE NOT NULL, 
SESSO_DOT CHAR(1), 
CITTA_DOT VARCHAR(20), 
VIA_DOT VARCHAR(30), 
CDM CHAR(4) NOT NULL UNIQUE,
TELEFONO_DOT CHAR(10) NOT NULL UNIQUE, 
PROV_DOT CHAR(2) NOT NULL, 
CONSTRAINT CHECK_SDOT CHECK(SESSO_DOT IN ('M','F'))
);

CREATE TABLE DONATORE (
CF_DON CHAR(16) PRIMARY KEY, 
NOME_DON VARCHAR(15) NOT NULL, 
COGNOME_DON VARCHAR(30) NOT NULL, 
DN_DON DATE,  
CITTA_DON VARCHAR(20), 
VIA_DON VARCHAR(30), 
G_SANGUIGNO VARCHAR(3) NOT NULL, 
OCCHI VARCHAR(10),
PESO NUMBER,  
CAPELLI VARCHAR(10),
ANONIMATO CHAR(2) NOT NULL, 
ETNIA VARCHAR(15), 
ALTEZZA NUMBER,  
TELEFONO_DON CHAR(10) NOT NULL UNIQUE, 
PROV_DON CHAR(2) NOT NULL, 
CONSTRAINT CHECK_COLOREOCCHI CHECK (OCCHI IN ('BLU','AZZURRI','VERDI','MARRONI','NERI','GRIGI')),
CONSTRAINT CHECK_GS CHECK(G_SANGUIGNO IN ('0-','0+','A-','A+','B-','B+','AB-','AB+')),
CONSTRAINT CHECK_PESO CHECK((PESO>30) AND (PESO<150)),
CONSTRAINT CHECK_AN CHECK(ANONIMATO IN ('SI','NO')), 
CONSTRAINT CHECK_HE CHECK((ALTEZZA> 120) AND (ALTEZZA<220))
);

 
CREATE TABLE PAGAMENTO (
TIPO_PA VARCHAR(20) CHECK(TIPO_PA IN ('INSEMINAZIONE','FIALA')), 
FATTURA CHAR(10) PRIMARY KEY, 
DATAP DATE, 
METODOP VARCHAR(10), 
CF_CLI CHAR(16) NOT NULL, 
CONSTRAINTS EFFETTUA FOREIGN KEY(CF_CLI) REFERENCES CLIENTE(CF_CLI)
);

CREATE TABLE FIALA_SEME (
DATA_SEME DATE, 
ID_FIALA_SE CHAR(4) PRIMARY KEY,
CF_DON CHAR(16) NOT NULL, 
ID_CRIO NUMBER,  
COD_E_SPERMIOGRAMMA CHAR(8) NOT NULL, 
COD_E_GENETICO CHAR (8) NOT NULL,
COD_INS CHAR(8), 
FATTURA CHAR(10),
SANO CHAR(2) CHECK (SANO IN ('SI','NO')), 
CONSTRAINT CONNESSO FOREIGN KEY(FATTURA) REFERENCES PAGAMENTO(FATTURA)
);


CREATE TABLE FIALA_SANGUE (
DATA_SANGUE DATE,
ID_FIALA_SA CHAR(4) PRIMARY KEY,
CF_DON CHAR(16), 
CF_CLI CHAR(16),
COD_E_FERTILITA CHAR(8), 
COD_E_SANGUE CHAR(8), 
ID_CRIO_SANGUE NUMBER,
SANO CHAR(2) CHECK (SANO IN ('SI','NO'))
); 


CREATE TABLE CRIOCELLA( 
ID_CRIO NUMBER PRIMARY KEY, 
CAPIENZA_MAX NUMBER NOT NULL, 
TIPO VARCHAR (10) CHECK(TIPO IN ('SANGUE', 'SEME')),
CONSTRAINT CHECK_CM CHECK(CAPIENZA_MAX IN (20,40,60,80))
); 
 

CREATE TABLE INSEMINAZIONE (
COD_INS CHAR(8) PRIMARY KEY, 
TIPO_INS CHAR(3), 
FATTURA CHAR(10),
ID_PREN NUMBER NOT NULL,
CONSTRAINT CHECK_TI CHECK(TIPO_INS IN ('ICI','IUI')),
CONSTRAINT RELATIVO FOREIGN KEY(FATTURA) REFERENCES PAGAMENTO(FATTURA)
);

CREATE TABLE CARTELLA_CLINICA (
C_CLINICA CHAR(8) PRIMARY KEY, 
DATA_CREAZIONE DATE NOT NULL, 
DATA_CHIUSURA DATE, 
CF_DON CHAR(16) UNIQUE,
CF_CLI CHAR(16) UNIQUE,
CONSTRAINT POSSIEDE_CLIENTE FOREIGN KEY(CF_CLI) REFERENCES CLIENTE(CF_CLI),
CONSTRAINT POSSIEDE_DONATORE FOREIGN KEY(CF_DON) REFERENCES DONATORE(CF_DON)
); 

CREATE TABLE GENETICO (
COD_E_GENETICO CHAR (8) PRIMARY KEY, 
ID_PREN NUMBER NOT NULL, 
C_CLINICA CHAR(8) NOT NULL,
DATA_GEN DATE, 
IRT NUMBER NOT NULL, 
ESONE7 NUMBER NOT NULL CHECK(ESONE7 IN(1,0)), 
CARIOTIPO CHAR(4) NOT NULL, 
CONSTRAINT RIF_CC_GEN FOREIGN KEY(C_CLINICA) REFERENCES CARTELLA_CLINICA(C_CLINICA)
);

CREATE TABLE SPERMIOGRAMMA ( 
COD_E_SPERMIOGRAMMA CHAR(8) PRIMARY KEY,
ID_PREN NUMBER NOT NULL, 
C_CLINICA CHAR(8) NOT NULL,
DATA_E_SP DATE,
CNTZ NUMBER NOT NULL,
VOL NUMBER NOT NULL,
MOT NUMBER NOT NULL CHECK((MOT>0) AND (MOT<100)),
PH NUMBER NOT NULL,
CONSTRAINT RF_CC_SPE FOREIGN KEY(C_CLINICA) REFERENCES CARTELLA_CLINICA(C_CLINICA)
); 

CREATE TABLE SANGUE(
COD_E_SANGUE CHAR(8) PRIMARY KEY, 
ID_PREN NUMBER NOT NULL, 
C_CLINICA CHAR(8) NOT NULL, 
DATA_E_SA DATE,
TPHA NUMBER NOT NULL,
VLDRL NUMBER NOT NULL,
LINFOCITICD4 NUMBER NOT NULL,
CONSTRAINT RF_CC_SAN FOREIGN KEY(C_CLINICA) REFERENCES CARTELLA_CLINICA(C_CLINICA)
); 


CREATE TABLE FERTILITA(
COD_E_FERTILITA CHAR(8) PRIMARY KEY,
ID_PREN NUMBER NOT NULL, 
C_CLINICA CHAR(8) NOT NULL, 
DATA_E_FE DATE, 
PROLATTINA NUMBER NOT NULL,
FSH NUMBER NOT NULL,
CONSTRAINT RF_CC_FER FOREIGN KEY(C_CLINICA) REFERENCES CARTELLA_CLINICA(C_CLINICA)
); 

CREATE TABLE TURNO(
COD_TURNO NUMBER PRIMARY KEY,
INIZIO_TURNO DATE NOT NULL CHECK (TO_CHAR(INIZIO_TURNO,'HH24:MI:SS')>'08:29:00'),
FINE_TURNO DATE NOT NULL CHECK (TO_CHAR(FINE_TURNO,'HH24:MI:SS')<'20:31:00')  
); 

CREATE TABLE SALA(
NUM_SALA NUMBER PRIMARY KEY, 
ALA CHAR(1) NOT NULL,
PIANO NUMBER NOT NULL
); 

CREATE TABLE PRENOTAZIONE(
TIPO_PREN VARCHAR(20), 
DATA_ORA DATE NOT NULL, 
ID_PREN NUMBER PRIMARY KEY, 
NUM_SALA NUMBER,
CF_DON CHAR(16), 
CF_CLI CHAR(16),
CONSTRAINT P_CLIENTE FOREIGN KEY (CF_CLI) REFERENCES CLIENTE(CF_CLI), 
CONSTRAINT P_DONATORE FOREIGN KEY (CF_DON) REFERENCES DONATORE(CF_DON),
CONSTRAINT SI_ESEGUE_IN FOREIGN KEY (NUM_SALA) REFERENCES SALA(NUM_SALA), 
CONSTRAINT TIPO_PRENOTAZIONE CHECK(TIPO_PREN IN('DONAZIONE','INSEMINAZIONE','SPERMIOGRAMMA','GENETICO','SANGUE','FERTILITA'))
);


CREATE TABLE LAVORA_IN(
CF_DOT CHAR(16), 
NUM_SALA NUMBER,
DATA_ORA DATE, 
CONSTRAINT PK_LAVORA_IN PRIMARY KEY (CF_DOT,NUM_SALA, DATA_ORA),
CONSTRAINT FK_LAVORA_IN_DOT FOREIGN KEY(CF_DOT) REFERENCES DOTTORE(CF_DOT),
CONSTRAINT FK_LAVORA_IN_SALA FOREIGN KEY(NUM_SALA) REFERENCES SALA(NUM_SALA)
);




CREATE TABLE EFFETTUA_T(
DATA_T DATE, 
CF_DOT CHAR(16),
COD_TURNO NUMBER,
CONSTRAINT TURNO_DOT_PRE FOREIGN KEY(CF_DOT) REFERENCES DOTTORE(CF_DOT), 
CONSTRAINT TURNO_COD_PRE FOREIGN KEY(COD_TURNO) REFERENCES TURNO(COD_TURNO), 
CONSTRAINT PK_T_PRE PRIMARY KEY (CF_DOT,COD_TURNO, DATA_T)
);




ALTER TABLE FIALA_SEME ADD CONSTRAINT CONSERVATA FOREIGN KEY(ID_CRIO) REFERENCES CRIOCELLA(ID_CRIO);
ALTER TABLE FIALA_SEME ADD CONSTRAINT DA_SEME FOREIGN KEY(COD_E_SPERMIOGRAMMA) REFERENCES SPERMIOGRAMMA(COD_E_SPERMIOGRAMMA);
ALTER TABLE FIALA_SEME ADD CONSTRAINT DA_GENETICO FOREIGN KEY(COD_E_GENETICO) REFERENCES GENETICO(COD_E_GENETICO); 
ALTER TABLE FIALA_SEME ADD CONSTRAINT UILIZZA FOREIGN KEY (COD_INS) REFERENCES INSEMINAZIONE(COD_INS);


ALTER TABLE FIALA_SANGUE ADD CONSTRAINT DA_FERTILITA FOREIGN KEY(COD_E_FERTILITA) REFERENCES FERTILITA(COD_E_FERTILITA); 
ALTER TABLE FIALA_SANGUE ADD CONSTRAINT DA_SANGUE FOREIGN KEY(COD_E_SANGUE) REFERENCES SANGUE(COD_E_SANGUE); 


ALTER TABLE GENETICO ADD CONSTRAINT P_GENETICO FOREIGN KEY(ID_PREN) REFERENCES PRENOTAZIONE(ID_PREN);


ALTER TABLE SANGUE ADD CONSTRAINT P_SANGUE FOREIGN KEY(ID_PREN) REFERENCES PRENOTAZIONE(ID_PREN);


ALTER TABLE SPERMIOGRAMMA ADD CONSTRAINT P_SPERMIOGRAMMA FOREIGN KEY(ID_PREN) REFERENCES PRENOTAZIONE(ID_PREN);


ALTER TABLE FERTILITA ADD CONSTRAINT P_FERTILITA FOREIGN KEY(ID_PREN) REFERENCES PRENOTAZIONE(ID_PREN); 
ALTER TABLE FIALA_SANGUE ADD CONSTRAINT CONSERVATO_SANGUE FOREIGN KEY(ID_CRIO_SANGUE) REFERENCES CRIOCELLA(ID_CRIO);


ALTER TABLE INSEMINAZIONE ADD CONSTRAINT P_INSEMINAZIONE FOREIGN KEY(ID_PREN) REFERENCES PRENOTAZIONE(ID_PREN);







