


CREATE OR REPLACE FUNCTION GET_ID_CRIO (TIPO NUMBER) RETURN NUMBER IS 
ID_DA_RESTITUIRE NUMBER;
ID_DISPONIBILE NUMBER;

SPAZIO_NON_DISPONIBILE EXCEPTION;
BEGIN 
--1 = SANGUE, 2= SEME.
IF (TIPO = 1)

THEN 


	
		SELECT COUNT(*) INTO ID_DISPONIBILE FROM(
		SELECT CRIO.ID_CRIO
		FROM CRIOCELLA CRIO
		WHERE CRIO.TIPO = 'SANGUE' 
		GROUP BY CRIO.ID_CRIO
		HAVING 
		(SELECT COUNT(*)
		FROM CRIOCELLA C JOIN FIALA_SANGUE F ON C.ID_CRIO = F.ID_CRIO_SANGUE
		WHERE C.ID_CRIO = CRIO.ID_CRIO) < MAX(CRIO.CAPIENZA_MAX)
		ORDER BY CRIO.ID_CRIO) WHERE ROWNUM=1;
		
		IF (ID_DISPONIBILE = 0)
		THEN RAISE SPAZIO_NON_DISPONIBILE;
		END IF;
		
		SELECT ID_CRIO INTO ID_DA_RESTITUIRE FROM(
		SELECT CRIO.ID_CRIO
		FROM CRIOCELLA CRIO
		WHERE CRIO.TIPO = 'SANGUE' 
		GROUP BY CRIO.ID_CRIO
		HAVING 
		(SELECT COUNT(*)
		FROM CRIOCELLA C JOIN FIALA_SANGUE F ON C.ID_CRIO = F.ID_CRIO_SANGUE
		WHERE C.ID_CRIO = CRIO.ID_CRIO) < MAX(CRIO.CAPIENZA_MAX)
		ORDER BY CRIO.ID_CRIO) WHERE ROWNUM=1;
		
		RETURN ID_DA_RESTITUIRE;
		
		
ELSE 

		SELECT COUNT(*) INTO ID_DISPONIBILE FROM(
		SELECT CRIO.ID_CRIO
		FROM CRIOCELLA CRIO
		WHERE CRIO.TIPO = 'SEME' 
		GROUP BY CRIO.ID_CRIO
		HAVING 
		(SELECT COUNT(*)
		FROM CRIOCELLA C JOIN FIALA_SEME F ON C.ID_CRIO = F.ID_CRIO
		WHERE C.ID_CRIO = CRIO.ID_CRIO) < MAX(CRIO.CAPIENZA_MAX)
		ORDER BY CRIO.ID_CRIO) WHERE ROWNUM=1;
		
		IF (ID_DISPONIBILE = 0)
		THEN RAISE SPAZIO_NON_DISPONIBILE;
		END IF;
		
		SELECT ID_CRIO INTO ID_DA_RESTITUIRE FROM(
		SELECT CRIO.ID_CRIO
		FROM CRIOCELLA CRIO
		WHERE CRIO.TIPO = 'SEME' 
		GROUP BY CRIO.ID_CRIO
		HAVING 
		(SELECT COUNT(*)
		FROM CRIOCELLA C JOIN FIALA_SEME F ON C.ID_CRIO = F.ID_CRIO
		WHERE C.ID_CRIO = CRIO.ID_CRIO) < MAX(CRIO.CAPIENZA_MAX)
		ORDER BY CRIO.ID_CRIO) WHERE ROWNUM=1;
		
		RETURN ID_DA_RESTITUIRE;
		
END IF;
EXCEPTION
WHEN SPAZIO_NON_DISPONIBILE
THEN RAISE_APPLICATION_ERROR(-20595,'NON SI TROVA SPAZIO NELLE CRIOCELLE!');

END; 
/

SHO ERR; 