CREATE USER Admin IDENTIFIED BY 00007336
GRANT ALL PRIVILEGES TO Admin; 


-- CREAZIONE DEL PROPRIETARIO E DEI SUOI PERMESSI 
CREATE USER PROPRIETARIO IDENTIFIED BY PROP; 
GRANT CREATE SESSION TO PROPRIETARIO; 
GRANT EXECUTE ON INSERISCI_CRIOCELLA TO PROPRIETARIO; 
GRANT INSERT  ON DOTTORE TO PROPRIETARIO; 
GRANT UPDATE  ON DOTTORE TO PROPRIETARIO; 
GRANT DELETE  ON DOTTORE TO PROPRIETARIO;
GRANT UPDATE  ON CRIOCELLA TO PROPRIETARIO; 
GRANT DELETE  ON CRIOCELLA TO PROPRIETARIO; 



-- CREAZIONE DEL DOTTORE E DEI SUOI PERMESSI
CREATE USER DOTTORE IDENTIFIED BY DOT; 
GRANT CREATE SESSION TO DOTTORE; 
GRANT EXECUTE ON INSERISCI_FIALA_SANGUE TO DOTTORE;
GRANT EXECUTE ON INSERISCI_FIALA_SEME TO DOTTORE;  
GRANT EXECUTE ON INSERT_ES_SANGUE TO DOTTORE; 
GRANT EXECUTE ON INSERT_ES_SPERM TO DOTTORE; 
GRANT EXECUTE ON INSERT_ES_GENET TO DOTTORE; 
GRANT EXECUTE ON INSERT_ES_FERT TO DOTTORE;
GRANT EXECUTE ON INSERT_INSEMINAZIONE TO DOTTORE;  
GRANT SELECT  ON FIALA_SEME TO DOTTORE; 
GRANT SELECT  ON FIALA_SANGUE TO DOTTORE; 
GRANT SELECT  ON CRIOCELLA TO DOTTORE; 
GRANT SELECT  ON INSEMINAZIONE TO DOTTORE; 
GRANT SELECT  ON PREN_GIORNALIERE TO DOTTORE; 
GRANT SELECT  ON ESAME_GENETICO TO DOTTORE; 
GRANT SELECT  ON ESAME_SANGUE TO DOTTORE; 
GRANT SELECT  ON ESAME_SPERMIOGRAMMA TO DOTTORE; 
GRANT SELECT  ON ESAME_FERTILITA TO DOTTORE; 
GRANT UPDATE  ON FIALA_SEME TO DOTTORE; 
GRANT UPDATE  ON FIALA_SANGUE TO DOTTORE; 
GRANT UPDATE  ON GENETICO TO DOTTORE; 
GRANT UPDATE  ON SPERMIOGRAMMA TO DOTTORE; 
GRANT UPDATE  ON SANGUE TO DOTTORE; 
GRANT UPDATE  ON FERTILITA TO DOTTORE; 
GRANT DELETE  ON FIALA_SEME TO DOTTORE; 
GRANT DELETE  ON FIALA_SANGUE TO DOTTORE; 
GRANT DELETE  ON GENETICO TO DOTTORE; 
GRANT DELETE  ON SPERMIOGRAMMA TO DOTTORE; 
GRANT DELETE  ON SANGUE TO DOTTORE; 
GRANT DELETE  ON FERTILITA TO DOTTORE; 


-- CREAZIONE DELLA SEGRETERIA E DEI SUOI PERMESSI
CREATE USER SEGRETERIA IDENTIFIED BY SEG; 
GRANT CREATE SESSION TO SEGRETERIA; 
GRANT EXECUTE ON INSERISCI_PRENOTAZIONE TO SEGRETERIA; 
GRANT EXECUTE ON ELIMINA_PRENOTAZIONE TO SEGRETERIA; 
GRANT EXECUTE ON INSERISCI_CLIENTE TO SEGRETERIA; 
GRANT EXECUTE ON INSERISCI_DONATORE TO SEGRETERIA; 
GRANT EXECUTE ON ACQUISTO_FIALA TO SEGRETERIA; 
GRANT EXECUTE ON INSERISCI_PAG_INS TO SEGRETERIA;  
GRANT SELECT  ON PRENOTAZIONI_DISPONIBILI TO SEGRETERIA;
GRANT SELECT  ON DONATORI_DISPONIBILI TO SEGRETERIA; 
GRANT UPDATE  ON PRENOTAZIONE TO SEGRETERIA; 
GRANT UPDATE  ON DONATORE TO SEGRETERIA; 
GRANT UPDATE  ON CLIENTE TO SEGRETERIA; 
GRANT SELECT  ON CARTELLA_CLINICA TO SEGRETERIA; 
GRANT UPDATE  ON CARTELLA_CLINICA TO SEGRETERIA;  


-- CREAZIONE DEL CLIENTE 
CREATE USER CLIENTE IDENTIFIED BY CLI; 
GRANT CREATE SESSION TO CLIENTE; 
GRANT SELECT ON VISITA_DONATORI TO CLIENTE; 
GRANT SELECT ON VISITA_DONATORI_ANONIMI TO CLIENTE;  
GRANT SELECT ON ESAME_SANGUE TO CLIENTE; 
GRANT SELECT ON ESAME_FERTILITA TO CLIENTE; 
GRANT SELECT ON VISUALIZZA_PRENOTAZIONI TO CLIENTE; 

-- CREAZIONE DEL DONATORE 
CREATE USER DONATORE IDENTIFIED BY DON; 
GRANT CREATE SESSION TO DONATORE; 
GRANT SELECT ON ESAME_GENETICO TO DONATORE; 
GRANT SELECT ON ESAME_SPERMIOGRAMMA TO DONATORE; 
GRANT SELECT ON ESAME_SANGUE TO DONATORE; 
GRANT SELECT ON VISUALIZZA_PRENOTAZIONI TO DONATORE; 
