--VISUALIZZARE GLI SLOT ANCORA DISPONIBILI PER LA PRENOTAZIONE DELLA SETTIMANA CORRENTE 

CREATE OR REPLACE VIEW PRENOTAZIONI_DISPONIBILI AS
SELECT TO_CHAR(DATA_ORA,'DD/MM/YYYY HH24:MI') AS ORARIO, NUM_SALA AS SALA FROM PRENOTAZIONE 
WHERE  CF_CLI IS NULL AND CF_DON IS NULL AND DATA_ORA>=SYSDATE AND DATA_ORA<(
SELECT NEXT_DAY(TRUNC(SYSDATE,'DAY'),'DOMENICA') FROM DUAL); 

/ 
 
SHO ERR; 

-- MOSTARE IL NOME E IL COGNOME DEI DONATORI CON ALMENO UNA FIALA DISPONIBILE

CREATE OR REPLACE VIEW DONATORI_DISPONIBILI AS 
SELECT D.NOME_DON AS NOME, D.COGNOME_DON AS COGNOME
FROM DONATORE D JOIN FIALA_SEME FS ON FS.CF_DON=D.CF_DON 
WHERE FS.SANO='SI' AND FS.FATTURA IS NULL AND FS.COD_INS IS NULL; 
/

SHO ERR; 

-- VISUALIZZARE TUTTI I DONATORI CHE SONO LEGALMENTE RINTRACCIABILI 
CREATE OR REPLACE VIEW VISITA_DONATORI AS 
SELECT NOME_DON AS NOME, COGNOME_DON AS COGNOME, G_SANGUIGNO, OCCHI, PESO, CAPELLI, ETNIA, ALTEZZA, TELEFONO_DON AS CONTATTO FROM DONATORE WHERE ANONIMATO='NO'; 

/ 

SHO ERR; 
-- VISUALIZZARE I DONATORI CHE NON SONO LEGALMENTE RINTRACCIABILI

CREATE OR REPLACE VIEW VISITA_DONATORI_ANONIMI AS
SELECT NOME_DON AS NOME, COGNOME_DON AS COGNOME, G_SANGUIGNO, OCCHI, PESO, CAPELLI, ETNIA, ALTEZZA FROM DONATORE WHERE ANONIMATO='SI'; 

/
SHO ERR; 

-- VISUALIZZARE LE PRENOTAZIONI DEL GIORNO E I DOTTORI OCCUPATI E IN QUALE SALA -- DA VEDERE SE FUNZIONA

CREATE OR REPLACE VIEW PREN_GIORNALIERE AS 
SELECT DISTINCT D.NOME_DOT, D.COGNOME_DOT, TO_CHAR(L.DATA_ORA,'HH24:MI') AS ORA, S.NUM_SALA FROM ((PRENOTAZIONE P JOIN SALA S ON S.NUM_SALA=P.NUM_SALA) JOIN LAVORA_IN L ON L.NUM_SALA=S.NUM_SALA) JOIN DOTTORE D ON L.CF_DOT=D.CF_DOT
WHERE TO_DATE(L.DATA_ORA,'DD/MM/YYYY')=TO_DATE(SYSDATE,'DD/MM/YYYY'); 


-- VISUALIZZARE I RISULTATI DELL'ESAME GENETICO 

CREATE OR REPLACE VIEW ESAME_GENETICO AS 
SELECT  C_CLINICA, IRT, ESONE7, CARIOTIPO FROM GENETICO; 


-- VISUALIZZARE I RISULTATI DELL'ESAME DEL SANGUE 

CREATE OR REPLACE VIEW ESAME_SANGUE AS 
SELECT C_CLINICA, TPHA, VLDRL, LINFOCITICD4 FROM SANGUE; 

-- VISUALIZZARE I RISULTATI DELL'ESAME SPERMIOGRAMMA

CREATE OR REPLACE VIEW ESAME_SPERMIOGRAMMA AS 
SELECT C_CLINICA, CNTZ, VOL, MOT, PH FROM SPERMIOGRAMMA; 

-- VISUALIZZARE I RISULTATI DELL'ESAME FERTILITA

CREATE OR REPLACE VIEW ESAME_FERTILITA AS 
SELECT C_CLINICA, PROLATTINA, FSH FROM FERTILITA; 

/
SHO ERR; 


-- VISUALIZZARE PRENOTAZIONI DEL CLIENTE O DEL DONATORE 
CREATE OR REPLACE VIEW VISUALIZZA_PRENOTAZIONI AS 
SELECT ID_PREN, DATA_ORA, CF_DON, CF_CLI, NUM_SALA FROM PRENOTAZIONE WHERE DATA_ORA>=SYSDATE AND (CF_DON IS NOT NULL OR CF_CLI IS NOT NULL); 